CREATE USER Proyecto1 IDENTIFIED BY Proyecto1;

GRANT CREATE SESSION TO Proyecto1;
GRANT CONNECT, RESOURCE TO Proyecto1;
GRANT CREATE VIEW TO Proyecto1;
GRANT CREATE SEQUENCE TO Proyecto1;

ALTER USER Proyecto1 QUOTA UNLIMITED ON USERS;