@startchen 07-integrated-model
title ENTERPRISE DATA MODEL
left to right direction
skinparam ranksep 10
!theme sunlust
entity DEPARTMENT {
}
entity EMPLOYEE {
}
entity PROJECT {
}
entity PART {
}
entity SUPPLIER {
}

relationship DEP_EMP {
}
relationship DEP_MAN {
}
relationship EMP_SUP {
}
relationship EMP_PRO {
}
relationship PRO_PAR_SUP {
}
relationship COMPONENT {
}

DEPARTMENT -1- DEP_EMP
DEP_EMP -N- EMPLOYEE

DEPARTMENT -1- DEP_MAN
DEP_MAN -N- EMPLOYEE

EMPLOYEE -1- EMP_SUP
EMP_SUP -N- EMPLOYEE

EMPLOYEE -1- EMP_PRO
EMP_PRO -N- PROJECT

PROJECT -N- PRO_PAR_SUP
PRO_PAR_SUP -N- PART
SUPPLIER -N- PRO_PAR_SUP

PART -N- COMPONENT
COMPONENT -N- PART

@endchen